services:
  spring:
    image: amazoncorretto:21 
    container_name: spring 
    command: sh -c "mkdir -p /usr/share/api && java -jar /usr/share/api/beauty_barreto.jar --spring.profiles.active=prod"
    volumes:
      - /usr/share/api:/usr/share/api  
    ports:
      - "8080:8080"
    environment:
      - WEB_URL_ENDPOINT=http://${load_balancer_dns}
      - CREDENTIALS_FILE_PATH=file:/usr/share/api/credentials.json
      - DATABASE_IP=${database_ip}
    networks:
      - app-net
    depends_on:
      - redisinsight
      - rabbitmq
      
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-net

  consumer:
    image: 'python:3.12-slim'
    container_name: consumer
    volumes:
      - /usr/share/consumer/:/usr/share/consumer/
    command: >
      sh -c "apt-get update && pip install -r /usr/share/consumer/requirements.txt && python /usr/share/consumer/consumer.py"
    environment:
      - RABBITMQ_URL=amqp://myuser:secret@rabbitmq:5672/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASSWORD=secret
      
      - GMAIL_PASSWORD=$${GMAIL_PASSWORD}

      - DB_HOST=${database_ip}
      - DB_USER=root
      - DB_PASSWORD=infra
      - DB_NAME=grupo4
    networks:
      - app-net
    depends_on:
      - rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis
    command: [ "redis-server", "--save", "60", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - app-net
    volumes:
      - redisinsight_data:/data

networks:
  app-net:
    driver: bridge

volumes:
  redis_data:
  redisinsight_data:
