services:
  web_server:
    image: nginx:latest
    container_name: web_server
    
    ports:
      - "80:80"
    
    volumes:
      - /home/ubuntu/frontend:/usr/share/nginx/html
      - /home/ubuntu/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    restart: unless-stopped