services:
  api:
    image: amazoncorretto:21 
    container_name: api-spring 
    command: sh -c "mkdir -p /usr/share/api && java -jar /usr/share/api/beauty_barreto.jar --spring.profiles.active=prod"
    volumes:
      - /usr/share/api:/usr/share/api  
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      
  rabbitmq:
    image: 'rabbitmq:3.13-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'
      - '15672:15672'
